#!/usr/bin/env python3
"""
Migration 006: Add narrative insights fields to post_match_audits.

These fields store the human-readable explanations of why predictions
succeeded or failed, generated by the reasoning engine.
"""

import asyncio
import os

from sqlalchemy import text

# Get database URL from environment
DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable is required")


async def run_migration():
    """Add narrative insights columns to post_match_audits table."""
    from sqlalchemy.ext.asyncio import create_async_engine

    # Convert postgres:// to postgresql+asyncpg://
    db_url = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://")
    engine = create_async_engine(db_url)

    async with engine.begin() as conn:
        # Check if narrative_insights column already exists
        result = await conn.execute(text("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns
                WHERE table_name = 'post_match_audits' AND column_name = 'narrative_insights'
            )
        """))
        exists = result.scalar()

        if exists:
            print("Column 'narrative_insights' already exists, skipping migration")
            return

        print("Adding narrative insights columns to post_match_audits...")

        # narrative_insights - JSON array of insight objects
        await conn.execute(text("""
            ALTER TABLE post_match_audits ADD COLUMN narrative_insights JSONB
        """))
        print("  Added: narrative_insights")

        # momentum_analysis - JSON object with momentum data
        await conn.execute(text("""
            ALTER TABLE post_match_audits ADD COLUMN momentum_analysis JSONB
        """))
        print("  Added: momentum_analysis")

        print("\nMigration 006 completed successfully!")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(run_migration())
